package(default_visibility = ["//visibility:public"])

cc_toolchain_suite(
    name = "arm_none_eabi_suite",
    toolchains = {
        "arm_none_eabi_10_3": "@arm_none_eabi_10_3//:arm_none_eabi_toolchain",
        "arm_none_eabi_11_2": "@arm_none_eabi_11_2//:arm_none_eabi_toolchain",
    },
)
